from pontozero_app.modelos.entidades.endereco import Endereco
from pontozero_app.modelos.entidades.instituicao import Instituicao
from pontozero_app.modelos.entidades.curso import Curso
from pontozero_app.modelos.entidades.empresa import Empresa
from pontozero_app.modelos.entidades.curriculo import Curriculo
from pontozero_app.modelos.entidades.pessoa import Pessoa
from pontozero_app.modelos.entidades.trabalho import Trabalho
from pontozero_app.modelos.entidades.estudante import Estudante
from pontozero_app.modelos.entidades.vaga import Vaga
from pontozero_app.modelos.entidades.professor import Professor
from pontozero_app.modelos.entidades.escola import Escola

from pontozero_app.modelos.repositorios.base_repositorio import BaseRepositorio
from pontozero_app.modelos.repositorios.repositorio_empresa import RepositorioEmpresa
from pontozero_app.modelos.repositorios.repositorio_estudante import RepositorioEstudante
from pontozero_app.modelos.repositorios.repositorio_vaga import RepositorioVaga
from pontozero_app.modelos.repositorios.repositorio_escola import RepositorioEscola
from pontozero_app.modelos.repositorios.repositorio_professor import RepositorioProfessor
from pontozero_app.modelos.repositorios.repositorio_trabalho import RepositorioTrabalho
from pontozero_app.modelos.repositorios.repositorio_curso import RepositorioCurso
from pontozero_app.modelos.repositorios.repositorio_curriculo import RepositorioCurriculo
from pontozero_app.modelos.repositorios.repositorio_abstract_factory import RepositorioFactory


from pontozero_app.modelos.cadastros.cadastro_empresa import CadastroEmpresa
from pontozero_app.modelos.cadastros.cadastro_estudante import CadastroEstudante
from pontozero_app.modelos.cadastros.cadastro_vaga import CadastroVaga
from pontozero_app.modelos.cadastros.cadastro_pessoa import CadastroPessoa
from pontozero_app.modelos.cadastros.cadastro_instituicao import CadastroInstituicao

from pontozero_app.modelos.controladores.controlador_empresa import ControladorEmpresa
from pontozero_app.modelos.controladores.controlador_estudante import ControladorEstudante
from pontozero_app.modelos.controladores.controlador_vaga import ControladorVaga

from pontozero_app.modelos.fachada.fachada import Fachada




